services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: macros_tracker
      POSTGRES_USER: macros_user
      POSTGRES_PASSWORD: macros_password
    ports:
      - "5432:5432"